apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n8lxwaclc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n8lxwaclc-go 
  name: n8lxwaclc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: n8lxwaclc-go 
