apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: n8lxwaclc-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-d9adfbc7b1.ywjl.p3.openshiftapps.com/rhtap/rhtap-qe:9ea67bda1011cf571542dab8faf6f19de7d04e61@sha256:aece62785f21335ad4062cdba8e60ffa72b42bbb6679ba892afd044a58de9273
          name: container-image
